services:
  - type: web
    name: mrlb-biryani-api
    runtime: node
    rootDir: apps/api
    buildCommand: npm install && npx prisma generate
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: "4000"
