import React,{useEffect,useState} from "react";
import {View,Text,Image,TouchableOpacity,FlatList,StyleSheet,SafeAreaView,TextInput,ActivityIndicator} from "react-native";
import {NavigationContainer} from "@react-navigation/native";
import {createNativeStackNavigator} from "@react-navigation/native-stack";

const API="http://localhost:4000";
const logo=require("./assets/mrlb-logo.png");
const demo=[
 {id:"1",name:"Chicken Biryani",description:"Aromatic basmati rice with tender chicken and signature spices.",price:169,image:"https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=900&q=80"},
 {id:"2",name:"Mutton Biryani",description:"Slow-cooked mutton layered with fragrant basmati rice.",price:249,image:"https://images.unsplash.com/photo-1701579231373-6b5b8b1b2f1f?auto=format&fit=crop&w=900&q=80"}
];
function Splash({navigation}){useEffect(()=>{setTimeout(()=>navigation.replace("Home"),1500)},[]);return <View style={s.splash}><Image source={logo} style={s.logo}/><Text style={s.tag}>BIRYANI • DELIVERED HOT</Text><ActivityIndicator/></View>}
function Home({navigation}){const [q,setQ]=useState(""); const [cart,setCart]=useState([]); const items=demo.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())); const add=x=>setCart(c=>[...c,x]); return <SafeAreaView style={s.page}><View style={s.header}><Image source={logo} style={s.headerLogo}/><TouchableOpacity onPress={()=>navigation.navigate("Cart",{cart})}><Text style={s.cart}>Cart ({cart.length})</Text></TouchableOpacity></View><Text style={s.hero}>Hot, fragrant biryani{"\n"}at your doorstep 🍗</Text><TextInput placeholder="Search biryani..." value={q} onChangeText={setQ} style={s.search}/><Text style={s.section}>Popular</Text><FlatList data={items} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Image source={{uri:item.image}} style={s.food}/><View style={{flex:1,padding:12}}><Text style={s.name}>{item.name}</Text><Text style={s.desc}>{item.description}</Text><Text style={s.price}>₹{item.price}</Text><TouchableOpacity style={s.btn} onPress={()=>add(item)}><Text style={s.btnText}>ADD TO CART</Text></TouchableOpacity></View></View>}/></SafeAreaView>}
function Cart({route,navigation}){const [cart,setCart]=useState(route.params.cart||[]); const subtotal=cart.reduce((a,x)=>a+x.price,0); return <SafeAreaView style={s.page}><Text style={s.title}>Your Cart</Text>{cart.map((x,i)=><View style={s.row} key={i}><Text style={{fontWeight:"700"}}>{x.name}</Text><Text>₹{x.price}</Text></View>)}<View style={s.total}><Text>Subtotal</Text><Text>₹{subtotal}</Text></View><View style={s.total}><Text>Delivery</Text><Text>₹40</Text></View><View style={s.total}><Text style={s.grand}>Total</Text><Text style={s.grand}>₹{subtotal+40}</Text></View><TouchableOpacity style={s.btnBig} onPress={()=>navigation.navigate("Checkout",{cart})}><Text style={s.btnText}>PROCEED TO CHECKOUT</Text></TouchableOpacity></SafeAreaView>}
function Checkout({route,navigation}){const total=(route.params.cart||[]).reduce((a,x)=>a+x.price,0)+40; return <SafeAreaView style={s.page}><Text style={s.title}>Checkout</Text><Text style={s.label}>Delivery address</Text><View style={s.box}><Text>Kalyani, West Bengal</Text><Text style={s.muted}>Demo address — replace with saved/map address</Text></View><Text style={s.label}>Payment</Text>{["UPI","Card","Net Banking","Cash on Delivery"].map(x=><TouchableOpacity key={x} style={s.option}><Text>{x}</Text><Text>›</Text></TouchableOpacity>)}<Text style={s.muted}>Final payable: ₹{total}. Payment gateway integration is wired for gateway references, not card storage.</Text><TouchableOpacity style={s.btnBig} onPress={()=>navigation.replace("Success")}><Text style={s.btnText}>PLACE ORDER • ₹{total}</Text></TouchableOpacity></SafeAreaView>}
function Success({navigation}){return <View style={s.splash}><Text style={s.check}>✓</Text><Text style={s.title}>Order Confirmed!</Text><Text>Order MRLB-{Date.now().toString().slice(-8)}</Text><TouchableOpacity style={s.btnBig} onPress={()=>navigation.replace("Tracking")}><Text style={s.btnText}>TRACK ORDER</Text></TouchableOpacity></View>}
function Tracking(){return <SafeAreaView style={s.page}><Text style={s.title}>Track your order</Text>{["Order received","Accepted","Preparing","Ready for pickup","Out for delivery","Delivered"].map((x,i)=><View style={s.track} key={x}><Text style={s.dot}>{i<2?"✓":"•"}</Text><View><Text style={s.name}>{x}</Text><Text style={s.muted}>{i<2?"Completed":"Updates automatically when available"}</Text></View></View>)}</SafeAreaView>}
const Stack=createNativeStackNavigator();
export default function App(){return <NavigationContainer><Stack.Navigator screenOptions={{headerShown:false}}><Stack.Screen name="Splash" component={Splash}/><Stack.Screen name="Home" component={Home}/><Stack.Screen name="Cart" component={Cart}/><Stack.Screen name="Checkout" component={Checkout}/><Stack.Screen name="Success" component={Success}/><Stack.Screen name="Tracking" component={Tracking}/></Stack.Navigator></NavigationContainer>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#fff8ef",padding:18},splash:{flex:1,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",gap:16},logo:{width:270,height:270,resizeMode:"contain"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},headerLogo:{width:100,height:55,resizeMode:"contain"},cart:{fontWeight:"800"},hero:{fontSize:30,fontWeight:"900",marginVertical:22},search:{backgroundColor:"#fff",borderRadius:14,padding:15,borderWidth:1,borderColor:"#ead8c2"},section:{fontSize:22,fontWeight:"900",marginVertical:18},card:{backgroundColor:"#fff",borderRadius:18,overflow:"hidden",marginBottom:18,elevation:3},food:{width:"100%",height:190},name:{fontSize:18,fontWeight:"900"},desc:{color:"#756b61",marginVertical:6,lineHeight:20},price:{fontSize:19,fontWeight:"900",marginVertical:4},btn:{backgroundColor:"#c98516",padding:12,borderRadius:12,alignItems:"center"},btnBig:{backgroundColor:"#c98516",padding:16,borderRadius:14,alignItems:"center",marginTop:20},btnText:{color:"#fff",fontWeight:"900"},title:{fontSize:30,fontWeight:"900",marginBottom:20},row:{flexDirection:"row",justifyContent:"space-between",paddingVertical:14,borderBottomWidth:1,borderBottomColor:"#eadfd4"},total:{flexDirection:"row",justifyContent:"space-between",paddingVertical:12},grand:{fontSize:21,fontWeight:"900"},label:{fontWeight:"900",fontSize:16,marginTop:14,marginBottom:8},box:{backgroundColor:"#fff",padding:16,borderRadius:14},option:{backgroundColor:"#fff",padding:17,borderRadius:14,marginVertical:5,flexDirection:"row",justifyContent:"space-between"},muted:{color:"#756b61",marginTop:5},check:{fontSize:80,fontWeight:"900"},track:{flexDirection:"row",gap:15,paddingVertical:18,borderBottomWidth:1,borderBottomColor:"#eadfd4"},dot:{fontSize:24,fontWeight:"900",width:28}});
